CREATE TABLE IF NOT EXISTS `todo_record` (
`id` BIGINT AUTO_INCREMENT NOT NULL,
`title` VARCHAR(255) NOT NULL,
`completed` TINYINT NOT NULL,
`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`id`)
) ENGINE = InnoDB;
